### ISSUE TITLE
Unable to remove created user

### ISSUE THREAD

**Issue by mmaassen** [Atheos/Atheos#152]
**Describe the bug**
Unable to remove created user.
No error message in UI.

Error in nginx error log
```
==> /var/log/nginx/atheos_access.log <==
127.0.0.1 - - [26/Jan/2021:17:25:09 +0100] "POST /dialog.php HTTP/1.1" 200 156 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:84.0) Gecko/20100101 Firefox/84.0"

==> /var/log/nginx/atheos_error.log <==
2021/01/26 17:25:10 [error] 29063#29063: *1167 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ErrorException: Undefined property: User::$username in /var/www/atheos/components/user/class.user.php:131
Stack trace:
#0 /var/www/atheos/components/user/class.user.php(131): {closure}()
#1 /var/www/atheos/components/user/controller.php(81): User->delete()
#2 /var/www/atheos/controller.php(49): require('/var/www/code.j...')
#3 {main}
  thrown in /var/www/atheos/components/user/class.user.php on line 131" while reading response header from upstream, client: 127.0.0.1, server: atheos, request: "POST /controller.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "atheos"

==> /var/log/nginx/atheos_access.log <==
127.0.0.1 - - [26/Jan/2021:17:25:10 +0100] "POST /controller.php HTTP/1.1" 500 5 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:84.0) Gecko/20100101 Firefox/84.0"
```

**To Reproduce**
1. Go to 'users'
2. Click on 'user'
3. Press trash icon

**Expected behavior**
User was expected to be removed

**Screenshots**
not needed

**Desktop (please complete the following information):**
not relevant

**Additional context**

Used master from this git repo

Fix line 131 on components/user/class.user.php
```
unset($this->users[$username]);
```

**Comment by HLSiira** [comment]
Roger, fixed it as you recommended; looks good. Sorry you had to deal with that, let me know if there is anything else I can fix.
