### ISSUE TITLE
PHP 8.1 File menu fails to open

### ISSUE THREAD

**Issue by mbucas** [Atheos/Atheos#238]
On a new install with PHP 8.1, I can configure Atheos and create a project.
When I get the main page, I try to open the File menu on the project, but it doesn't show.

It works correctly in my main installation using PHP 7.4

**To Reproduce**
1. (On 2022-07-09) Get sources from main branch : git clone https://github.com/Atheos/Atheos.git code-main
2. Open web page https://xxx/test-php-81/code-main/
3. Configure Atheos with a new project
4. On main page, try to open File menu on the project
5. The File menu doesn't appear so I can't add files or directories

**Expected behavior**
The File menu should open

**Desktop :**
 - OS: Gentoo
 - Browser : Firefox 102

**Server :**
 - OS: Gentoo
 - Web Server : Apache 2.4.54
 - PHP : PHP 8.1.7
(I can provide the list of modules for each if necessary)

**Error message in Browser console**
```
Uncaught TypeError: self.fileMenu is undefined
    showFileMenu https://xxx/test-php-81/code-main/components/contextmenu/init.js:145
    init https://xxx/test-php-81/code-main/components/contextmenu/init.js:56
    eventHandler https://xxx/test-php-81/code-main/libraries/flux.js:52
    eventHandler https://xxx/test-php-81/code-main/libraries/flux.js:48
    on https://xxx/test-php-81/code-main/libraries/flux.js:98
    on https://xxx/test-php-81/code-main/libraries/flux.js:94
    on https://xxx/test-php-81/code-main/libraries/flux.js:162
    init https://xxx/test-php-81/code-main/components/contextmenu/init.js:49
    pub https://xxx/test-php-81/code-main/libraries/carbon.js:50
    init https://xxx/test-php-81/code-main/modules/system.js:44
    EventListener.handleEvent* https://xxx/test-php-81/code-main/modules/system.js:74
    <anonymous> https://xxx/test-php-81/code-main/modules/system.js:76
init.js:145:21
```

**Error message in Apache error_log**
```
[Sat Jul 09 11:19:10.454777 2022] [php:error] [pid 42359] [client 127.0.0.1:33990] PHP Fatal error:  Uncaught ErrorException: debug_backtrace(): Passing null to parameter #1 ($options) of type int is deprecated in /var/www/localhost/htdocs/test-php-81/code-main/traits/i18n.php:158
Stack trace:
#0 [internal function]: {closure}()
#1 /var/www/localhost/htdocs/test-php-81/code-main/traits/i18n.php(158): debug_backtrace()
#2 /var/www/localhost/htdocs/test-php-81/code-main/common.php(149): i18n->translate()
#3 /var/www/localhost/htdocs/test-php-81/code-main/components/contextmenu/class.contextmenu.php(193): i18n()
#4 /var/www/localhost/htdocs/test-php-81/code-main/components/contextmenu/controller.php(22): ContextMenu->loadMenus()
#5 /var/www/localhost/htdocs/test-php-81/code-main/controller.php(41): require('...')
#6 {main}
  thrown in /var/www/localhost/htdocs/test-php-81/code-main/traits/i18n.php on line 158
[Sat Jul 09 11:19:11.175646 2022] [php:error] [pid 42359] [client 127.0.0.1:33990] PHP Fatal error:  Uncaught ErrorException: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/localhost/htdocs/test-php-81/code-main/traits/path.php:29
Stack trace:
#0 [internal function]: {closure}()
#1 /var/www/localhost/htdocs/test-php-81/code-main/traits/path.php(29): str_replace()
#2 /var/www/localhost/htdocs/test-php-81/code-main/traits/path.php(48): Common::cleanPath()
#3 /var/www/localhost/htdocs/test-php-81/code-main/components/filemanager/controller.php(29): Common::getWorkspacePath()
#4 /var/www/localhost/htdocs/test-php-81/code-main/controller.php(41): require('...')
#5 {main}
  thrown in /var/www/localhost/htdocs/test-php-81/code-main/traits/path.php on line 29
```

**Comment by HLSiira** [comment]
Hey, sorry for the massively late reply. Is this still an issue on PHP8.1?

**Comment by mbucas** [comment]
Yes, there is still a problem.
If you need more information, I can provide it.

**Atheos update**
I've updated Atheos to the latest `main` commit:
```
$ git log --oneline |head -n1
9a1ddd6d Merge pull request #256 from Atheos/development
```

**Error message in Browser console**
```
constants.js:50:14
InstallTrigger est obsolète et sera supprimé prochainement.
system.js:60:7
   _____   __   __                        
  /  _  \_/  |_|  |__   ____  ____  ______
 /  /_\  \   __\  |  \_/ __ \/  _ \/  ___/
/    |    \  | |   Y  \  ___(  <_> )___ \ 
\____|__  /__| |___|  /\___  >____/____  >
        \/          \/     \/          \/ 
init.js:145:21
Uncaught TypeError: self.fileMenu is undefined
    showFileMenu https://lion.bucas.name/test-php-81/code-main/components/contextmenu/init.js:145
    init https://lion.bucas.name/test-php-81/code-main/components/contextmenu/init.js:56
    eventHandler https://lion.bucas.name/test-php-81/code-main/libraries/flux.js:52
    eventHandler https://lion.bucas.name/test-php-81/code-main/libraries/flux.js:48
    showFileMenu https://lion.bucas.name/test-php-81/code-main/components/contextmenu/init.js:145
    init https://lion.bucas.name/test-php-81/code-main/components/contextmenu/init.js:56
    eventHandler https://lion.bucas.name/test-php-81/code-main/libraries/flux.js:52
    forEach self-hosted:203
    eventHandler https://lion.bucas.name/test-php-81/code-main/libraries/flux.js:48
```

**Error message in Apache error_log**
```
[Mon Feb 20 19:29:47.999039 2023] [php:error] [pid 2938] [client 127.0.0.1:45988] PHP Fatal error:  Uncaught ErrorException: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/localhost/htdocs/test-php-81/code-main/common.php:167
Stack trace:
#0 [internal function]: {closure}()
#1 /var/www/localhost/htdocs/test-php-81/code-main/common.php(167): preg_replace()
#2 /var/www/localhost/htdocs/test-php-81/code-main/components/user/controller.php(18): POST()
#3 /var/www/localhost/htdocs/test-php-81/code-main/controller.php(41): require('...')
#4 {main}
  thrown in /var/www/localhost/htdocs/test-php-81/code-main/common.php on line 167
```

There are also many messages like this, but it seems unrelated:
```
[Mon Feb 20 19:28:27.166373 2023] [php:error] [pid 4063] [client 127.0.0.1:35368] PHP Parse error:  syntax error, unexpected identifier "debug", expecting "function" or "const" in /var/www/localhost/htdocs/test-php-81/code-main/components/codegit/traits/execute.php on line 23
```
