### ISSUE TITLE
PHP Error for some git part

### ISSUE THREAD

**Issue by MparkG** [Atheos/Atheos#277]
Two errroers:
```
Got error 'PHP message: PHP Fatal error:  Uncaught ErrorException: chdir(): No such file or directory (errno 2) in /var/www/atheos/components/codegit/class.git.php:53\nStack trace:\n#0 [internal function]: {closure}()\n#1 /var/www/atheos/components/codegit/class.git.php(53): chdir()\n#2 /var/www/atheos/components/codegit/controller.php(20): CodeGit->__construct()\n#3 /var/www/atheos/controller.php(41): require('...')\n#4 {main}\n  thrown in /var/www/atheos/components/codegit/class.git.php on line 53'

Got error 'PHP message: PHP Fatal error:  Uncaught ErrorException: Undefined variable $handle in /var/www/atheos/components/filemanager/class.filemanager.php:221\nStack trace:\n#0 /var/www/atheos/components/filemanager/class.filemanager.php(221): {closure}()\n#1 /var/www/atheos/components/filemanager/controller.php(70): Filemanager->index()\n#2 /var/www/atheos/controller.php(41): require('...')\n#3 {main}\n  thrown in /var/www/atheos/components/filemanager/class.filemanager.php on line 221'
```

Heres what it looks like:
![image](https://github.com/Atheos/Atheos/assets/26872340/9e0b7723-cad2-42ab-affe-316e4024d1dd)

I am running apache2 and php fpm with version 8.2

even if some folder wasnt there it should still function. (all project folders exist)

Idk what to do with this, how to fix it myself. as far as i saw, second errror arises from the path not resolving/existing...

**Comment by HLSiira** [comment]
Are you using the latest release of Atheos or a pull from the main branch?

**Comment by MparkG** [comment]
hi
Its a pull from git,
Should i be using release versions?

thx

Am 19. Mai 2023 12:45:32 MESZ schrieb Liam Siira ***@***.***>:
